f

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -15,11 +15,11 @@ jobs:
     name: CI
     runs-on: ubuntu-24.04
     timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        node-version-file:
-          - .node-version
+    # strategy:
+    #   fail-fast: false
+    #   matrix:
+    #     node-version-file:
+    #       - .node-version
     steps:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -28,19 +28,56 @@ jobs:
           ref: ${{ github.sha }}
           fetch-depth: 1
 
-      - name: Setup pnpm
-        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
-        with:
-          run_install: false
+      # - name: Setup pnpm
+      #   uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
+      #   with:
+      #     run_install: false
 
-      - name: Setup Node.js
-        id: setup-node
-        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
-        with:
-          node-version-file: ${{ matrix.node-version-file }}
-          cache: pnpm
+      # - name: Setup Node.js
+      #   id: setup-node
+      #   uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
+      #   with:
+      #     node-version-file: ${{ matrix.node-version-file }}
+      #     cache: pnpm
 
-      - env:
-          output_node_version: ${{ steps.setup-node.outputs.node-version }}
+      # - env:
+      #     output_node_version: ${{ steps.setup-node.outputs.node-version }}
+      #   run: |
+      #     echo "output_node_version: ${output_node_version}"
+
+      - name: Get current date
+        id: current-date
         run: |
-          echo "output_node_version: ${output_node_version}"
+          echo "monthly=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
+          echo "daily=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
+
+      - name: Restore ffmpeg cache
+        id: cache-ffmpeg
+        uses: actions/cache@v4
+        with:
+          path: |
+            /usr/local/bin/ffmpeg
+            /usr/local/bin/ffprobe
+          key: ffmpeg-cache-${{ runner.os }}-${{ runner.arch }}-${{ steps.current-date.outputs.daily }}
+          restore-keys: ffmpeg-cache-${{ runner.os }}-${{ runner.arch }}-${{ steps.current-date.outputs.monthly }}
+
+      - name: Install FFmpeg
+        if: ${{ steps.cache-ffmpeg.outputs.cache-hit != 'true' }}
+        run: |
+          BASE_DELAY=30
+          for i in {1..3}; do
+            BACKOFF_DELAY=$((BASE_DELAY * (2 ** (i - 1))))
+            echo "Attempt $i: Installing FFmpeg..."
+            curl -s -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz && \
+            tar -xf ffmpeg.tar.xz && \
+            mv ffmpeg-*-static/ffmpeg /usr/local/bin/ && \
+            mv ffmpeg-*-static/ffprobe /usr/local/bin/ && \
+            rm -rf ffmpeg.tar.xz ffmpeg-*-static/ && \
+            break || sleep $BACKOFF_DELAY
+            if [ $i -eq 3 ]; then
+              echo "Failed to install FFmpeg after 3 attempts"
+              exit 1
+            fi
+          done
+
+      - run: ffmpeg -version
