s

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -4,12 +4,18 @@ on:
   pull_request_target:
     branches:
       - main
+    types: # 他のワークフローで使用されるすべてのtypeを網羅すること
+      - opened
+      - synchronize
+      - reopened
+      - edited
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true
 
 permissions: {}
+  # pull-requests: read
   # checks: read
   # statuses: read
 
@@ -19,13 +25,54 @@ jobs:
     runs-on: ubuntu-24.04
     timeout-minutes: 60
     permissions:
+      pull-requests: read
       checks: read
       statuses: read
     steps:
-      - name: Run Merge Gatekeeper
-        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d # v1.2.1
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          self: Status Check
-          interval: 10
-          timeout: 3600
+      - name: Watch checks
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          while true; do
+            sleep 10
+
+            all_checks="$( \
+              gh pr --repo '${{ github.repository }}' \
+                checks '${{ github.event.number }}' \
+                --json bucket,workflow \
+                --jq 'map(select(.workflow != "${{ github.workflow }}"))' \
+            )"
+
+            failed_checks_length="$( \
+              jq -c 'map(select(.bucket == "fail" or .bucket == "cancel")) | length' \
+                <<< $all_checks \
+            )"
+
+            passed_checks_length="$( \
+              jq -c 'map(select(.bucket == "pass" or .bucket == "skipping")) | length' \
+                <<< $all_checks \
+            )"
+
+            pending_checks_length="$( \
+              jq -c 'map(select(.bucket == "pending")) | length' \
+                <<< $all_checks \
+            )"
+
+            echo "${failed_checks_length} failing, ${passed_checks_length} successful, and ${pending_checks_length} pending checks"
+
+            if [[ "$failed_checks_length" != "0" ]]; then
+              title="Some checks were not successful"
+              message="${failed_checks_length} failing checks"
+
+              echo "::error title=${title}::${message}"
+              exit 1
+            fi
+
+            if [[ "$pending_checks_length" == "0" ]]; then
+              title="All checks have passed"
+              message="${passed_checks_length} successful checks"
+
+              echo "::notice title=${title}::${message}"
+              exit 0
+            fi
+          done
